vich_uploader:
    db_driver: orm

    mappings:
        file:
            uri_prefix: /catalogs/imports
            upload_destination: '%kernel.project_dir%/public/catalogs/imports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer